services:
  redis:
    container_name: store
    image: redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data

volumes:
  redis:
    driver: local
